spring:
  profiles:
    active: dev
---
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: local
  config:
    activate:
      on-profile: dev
---
spring:
  config:
    activate:
      on-profile: nonprod
  data:
    mongodb:
      host: localhost
      port: 27017
      database: local
---
spring:
  config:
    activate:
      on-profile: prod
  data:
    mongodb:
      host: localhost
      port: 27017
      database: local